MM1_STEERING_MID = 1550
MM1_MAX_FORWARD = 1620  # Max is 2000
MM1_MAX_REVERSE = 1350
MM1_STOPPED_PWM = 1500
MM1_SHOW_STEERING_VALUE = False
MM1_SERIAL_PORT = '/dev/ttyS0'

THROTTLE_FORWARD_PWM = 410  # pwm value for max forward throttle
THROTTLE_STOPPED_PWM = 370  # pwm value for no movement
THROTTLE_REVERSE_PWM = 320  # pwm value for max reverse throttle

# SERVO_ESC|DC_STEER_THROTTLE|DC_TWO_WHEEL|DC_TWO_WHEEL_L298N|SERVO_HBRIDGE_PWM|PIGPIO_PWM|MM1|MOCK
DRIVE_TRAIN_TYPE = "PIGPIO_PWM"

JOYSTICK_MAX_THROTTLE = 1.0
JOYSTICK_THROTTLE_DIR = -1.0

CONTROLLER_TYPE = 'F710'  # (ps3|ps4)
DRIVE_LOOP_HZ = 20

if (CONTROLLER_TYPE == 'F710'):
    JOYSTICK_DEADZONE = 0.1

AUTO_CREATE_NEW_TUB = True
MAX_EPOCHS = 30

USE_SSD1306_128_32 = False  # Enable the SSD_1306 OLED Display

# DONKEY_GYM = True
# DONKEY_SIM_PATH = "remote"
# SIM_HOST="192.168.1.238"

CAMERA_VFLIP = True
CAMERA_HFLIP = True
